[project]
name = "deep-research"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "colorama>=0.4.6",
    "mcp>=1.3.0",
    "openai>=1.66.2",
]
